<?php
	switch ($lng) {
	case "en":
		echo "<header> &nbsp; Main page</header>";
		echo "<p>";
		echo ("Welcome to my pages on");
		echo (" $hostname. ");
		echo ("These pages are dedicated to testing of the most recent web and internet technologies.");
		echo "</p><p>";
		echo "These pages use HTML5 standard, so they can be properly viewed only in the most recent web browsers like Google Chrome, Mozilla Firefox 4.0 or Internet Explorer 9.";
		echo "</p><p>";
		echo "I don't use JavaScript for now. All dynamic content is generated by PHP on server-side, so your computer does only minimal work.";
		echo "</p>";
		break;
	default:
		echo "<header> &nbsp; Hlavní stránka</header>";
		echo "<p>Vítejte na mých stránkách na";
		echo (" $hostname. ");
		echo "Tyto stránky jsou určeny pro testování nejnovějších technologií webu a internetu</p>
		<p>Napsané jsou v HTML5,
		tudíž se správně zobrazují jen v nejnovějších webových prohlížečích
		jako Google Chrome, Mozilla Firefox 4.0 nebo Internet Explorer 9.</p>
		<p>Momentálně není použit JavaScript.
		Všechen dynamický obsah je generován pomocí PHP na straně serveru,
		tudíž váš počítač je zatěžován jen minimálně.</p>
		<p>Možná se ptáte, proč tyto stránky vypadají tak stroze a jednoduše,
		když mají využívat nejmodernějších webových a internetových technologií.
		Je tomu tak proto, že mám rád minimalismus, úsporu elektrické energie, úsporu přenosu dat
		atd. Tyto stránky by měly zaujmout obsahem, ne vzhledem - vzhled patří do marketingu
		a z mého pohledu není marketing nic jiného než zneužívání
		lidských vlastností, které mají ulehčit sblížení lidí.
		Pokud chcete vidět něco, co se vám líbí, tak se nenechte oblbnout reklamou
		a raději se podívejte na tvář někoho blízkého, zajděte si do přírody
		nebo navštivte nějakou obrazovou galerii :-)</p>";
	}
?>

